name: Radius
channels:
- conda-forge
dependencies:  
- voila=0.2.12
- ipykernel=5.3.4
- ipython=7.26.0
- ipywidgets=7.6.3
- numpy=1.20.3
- pandas=1.3.1
- matplotlib=3.4.2
- scipy=1.6.2
- seaborn=0.11.2
