name: Radius
channels:
- conda-forge
- defaults
dependencies:  
  - alabaster
  - appdirs
  - argh
  - arrow
  - astroid
  - async_generator
  - atomicwrites
  - attrs
  - autopep8
  - babel
  - backcall
  - bcrypt
  - binaryornot
  - black
  - blas
  - bleach
  - bottleneck
  - brotli
  - brotlipy
  - ca-certificates
  - certifi
  - cffi
  - chardet
  - click
  - cloudpickle
  - colorama
  - console_shortcut
  - cookiecutter
  - cryptography
  - cycler
  - decorator
  - defusedxml
  - diff-match-patch
  - docutils
  - entrypoints
  - flake8
  - fonttools
  - freetype
  - future
  - icc_rt
  - icu
  - idna
  - imagesize
  - importlib-metadata
  - importlib_metadata
  - inflection
  - intel-openmp
  - intervaltree
  - ipykernel
  - ipython
  - ipython_genutils
  - ipywidgets
  - isort
  - jedi
  - jinja2
  - jinja2-time
  - jpeg
  - jsonschema
  - jupyter_client
  - jupyter_core
  - jupyter_server
  - jupyterlab_pygments
  - jupyterlab_widgets
  - keyring=23.0.1
  - kiwisolver
  - lazy-object-proxy
  - libpng
  - libspatialindex
  - libtiff
  - lz4-c
  - m2w64-gcc-libgfortran
  - m2w64-gcc-libs
  - m2w64-gcc-libs-core
  - m2w64-gmp
  - m2w64-libwinpthread-git
  - markupsafe
  - matplotlib
  - matplotlib-base
  - matplotlib-inline
  - mccabe
  - mistune
  - mkl
  - mkl-service
  - mkl_fft
  - mkl_random
  - msys2-conda-epoch
  - munkres
  - mypy_extensions
  - nbclient
  - nbconvert
  - nbformat
  - nest-asyncio
  - notebook
  - numexpr
  - numpy
  - numpy-base
  - numpydoc
  - olefile
  - openssl
  - packaging
  - pandas
  - pandocfilters
  - paramiko
  - parso
  - pathspec
  - pexpect
  - pickleshare
  - pillow
  - pip
  - pluggy
  - poyo
  - prometheus_client
  - prompt-toolkit
  - psutil
  - ptyprocess
  - pycodestyle
  - pycparser
  - pydocstyle
  - pyflakes
  - pygments
  - pylint
  - pyls-black
  - pyls-spyder
  - pynacl
  - pyopenssl
  - pyparsing
  - pyqt
  - pyrsistent
  - pysocks
  - python=3.7.11
  - python-dateutil
  - python-jsonrpc-server
  - python-language-server
  - python-slugify
  - python_abi
  - pytz
  - pyyaml
  - pyzmq
  - qdarkstyle
  - qstylizer
  - qt
  - qtawesome
  - qtconsole
  - qtpy
  - regex
  - requests
  - requests-unixsocket
  - rope
  - rtree
  - scipy
  - seaborn
  - send2trash
  - setuptools
  - sip
  - six
  - sniffio
  - snowballstemmer
  - sortedcontainers
  - sphinx
  - sphinxcontrib-applehelp
  - sphinxcontrib-devhelp
  - sphinxcontrib-htmlhelp
  - sphinxcontrib-jsmath
  - sphinxcontrib-qthelp
  - sphinxcontrib-serializinghtml
  - spyder
  - spyder-kernels
  - sqlite
  - tabulate
  - testpath
  - text-unidecode
  - textdistance
  - three-merge
  - tinycss
  - tk
  - toml
  - tornado
  - traitlets
  - typed-ast
  - typing-extensions
  - typing_extensions
  - ujson=4.0.2
  - unidecode
  - urllib3
  - vc
  - voila
  - vs2015_runtime
  - watchdog
  - wcwidth
  - webencodings
  - wheel
  - whichcraft
  - widgetsnbextension
  - win_inet_pton
  - wincertstore
  - winpty
  - wrapt
  - xz
  - yaml
  - yapf
  - zipp
  - zlib
  - zstd
